// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.4
// source: config_sync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_OK   Code = 0
	Code_FAIL Code = 1
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "OK",
		1: "FAIL",
	}
	Code_value = map[string]int32{
		"OK":   0,
		"FAIL": 1,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_config_sync_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_config_sync_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{0}
}

type ServerStatus int32

const (
	ServerStatus_STARTING ServerStatus = 0
	ServerStatus_STARTED  ServerStatus = 1
	ServerStatus_FAILED   ServerStatus = 2
	ServerStatus_READY    ServerStatus = 3
)

// Enum value maps for ServerStatus.
var (
	ServerStatus_name = map[int32]string{
		0: "STARTING",
		1: "STARTED",
		2: "FAILED",
		3: "READY",
	}
	ServerStatus_value = map[string]int32{
		"STARTING": 0,
		"STARTED":  1,
		"FAILED":   2,
		"READY":    3,
	}
)

func (x ServerStatus) Enum() *ServerStatus {
	p := new(ServerStatus)
	*p = x
	return p
}

func (x ServerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_config_sync_proto_enumTypes[1].Descriptor()
}

func (ServerStatus) Type() protoreflect.EnumType {
	return &file_config_sync_proto_enumTypes[1]
}

func (x ServerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerStatus.Descriptor instead.
func (ServerStatus) EnumDescriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{1}
}

// 命令类型
type OrderType int32

const (
	OrderType_WRITEFILE OrderType = 0
	OrderType_EXECUTE   OrderType = 1
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "WRITEFILE",
		1: "EXECUTE",
	}
	OrderType_value = map[string]int32{
		"WRITEFILE": 0,
		"EXECUTE":   1,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_sync_proto_enumTypes[2].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_config_sync_proto_enumTypes[2]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{2}
}

type HeartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          string       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version      int32        `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	ServerStatus ServerStatus `protobuf:"varint,3,opt,name=serverStatus,proto3,enum=ServerStatus" json:"serverStatus,omitempty"`
}

func (x *HeartReq) Reset() {
	*x = HeartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_sync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartReq) ProtoMessage() {}

func (x *HeartReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartReq.ProtoReflect.Descriptor instead.
func (*HeartReq) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{0}
}

func (x *HeartReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HeartReq) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HeartReq) GetServerStatus() ServerStatus {
	if x != nil {
		return x.ServerStatus
	}
	return ServerStatus_STARTING
}

type Execute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderType OrderType `protobuf:"varint,1,opt,name=orderType,proto3,enum=OrderType" json:"orderType,omitempty"`
	FilePath  string    `protobuf:"bytes,2,opt,name=filePath,proto3" json:"filePath,omitempty"`
	Content   string    `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Id        string    `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	BinInfo   string    `protobuf:"bytes,5,opt,name=bin_info,json=binInfo,proto3" json:"bin_info,omitempty"`
	Args      []string  `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *Execute) Reset() {
	*x = Execute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_sync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Execute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Execute) ProtoMessage() {}

func (x *Execute) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Execute.ProtoReflect.Descriptor instead.
func (*Execute) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{1}
}

func (x *Execute) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_WRITEFILE
}

func (x *Execute) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Execute) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Execute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Execute) GetBinInfo() string {
	if x != nil {
		return x.BinInfo
	}
	return ""
}

func (x *Execute) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type UploadExecMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Ok  bool   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *UploadExecMsgReq) Reset() {
	*x = UploadExecMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_sync_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadExecMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadExecMsgReq) ProtoMessage() {}

func (x *UploadExecMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadExecMsgReq.ProtoReflect.Descriptor instead.
func (*UploadExecMsgReq) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{2}
}

func (x *UploadExecMsgReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadExecMsgReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UploadExecMsgReq) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type UploadExecMsgRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UploadExecMsgRes) Reset() {
	*x = UploadExecMsgRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_sync_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadExecMsgRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadExecMsgRes) ProtoMessage() {}

func (x *UploadExecMsgRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadExecMsgRes.ProtoReflect.Descriptor instead.
func (*UploadExecMsgRes) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{3}
}

type HeartRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R        *R         `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Version  int32      `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Executes []*Execute `protobuf:"bytes,3,rep,name=executes,proto3" json:"executes,omitempty"`
}

func (x *HeartRes) Reset() {
	*x = HeartRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_sync_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartRes) ProtoMessage() {}

func (x *HeartRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartRes.ProtoReflect.Descriptor instead.
func (*HeartRes) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{4}
}

func (x *HeartRes) GetR() *R {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *HeartRes) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HeartRes) GetExecutes() []*Execute {
	if x != nil {
		return x.Executes
	}
	return nil
}

// 系统设置
type APIConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port int32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *APIConf) Reset() {
	*x = APIConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_sync_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIConf) ProtoMessage() {}

func (x *APIConf) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIConf.ProtoReflect.Descriptor instead.
func (*APIConf) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{5}
}

func (x *APIConf) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type GetConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetConfigReq) Reset() {
	*x = GetConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_sync_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigReq) ProtoMessage() {}

func (x *GetConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigReq.ProtoReflect.Descriptor instead.
func (*GetConfigReq) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{6}
}

func (x *GetConfigReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetConfigRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R       *R       `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Config  string   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Version int32    `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	ApiConf *APIConf `protobuf:"bytes,4,opt,name=apiConf,proto3" json:"apiConf,omitempty"`
}

func (x *GetConfigRes) Reset() {
	*x = GetConfigRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_sync_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfigRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRes) ProtoMessage() {}

func (x *GetConfigRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRes.ProtoReflect.Descriptor instead.
func (*GetConfigRes) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{7}
}

func (x *GetConfigRes) GetR() *R {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *GetConfigRes) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *GetConfigRes) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetConfigRes) GetApiConf() *APIConf {
	if x != nil {
		return x.ApiConf
	}
	return nil
}

type R struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code Code   `protobuf:"varint,1,opt,name=code,proto3,enum=Code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *R) Reset() {
	*x = R{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_sync_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *R) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*R) ProtoMessage() {}

func (x *R) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use R.ProtoReflect.Descriptor instead.
func (*R) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{8}
}

func (x *R) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

func (x *R) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_config_sync_proto protoreflect.FileDescriptor

var file_config_sync_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69,
	0x0a, 0x08, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xa8, 0x01, 0x0a, 0x07, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x69, 0x6e, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x22, 0x44, 0x0a, 0x10, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x78,
	0x65, 0x63, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x45, 0x78, 0x65, 0x63, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x22, 0x5c,
	0x0a, 0x08, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x01, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x02, 0x2e, 0x52, 0x52, 0x01, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x08, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x52, 0x08, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x73, 0x22, 0x1d, 0x0a, 0x07,
	0x41, 0x50, 0x49, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x20, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x76, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a,
	0x01, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x02, 0x2e, 0x52, 0x52, 0x01, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x22, 0x0a, 0x07, 0x61, 0x70, 0x69, 0x43, 0x6f, 0x6e, 0x66, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x41, 0x50, 0x49, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x07, 0x61, 0x70,
	0x69, 0x43, 0x6f, 0x6e, 0x66, 0x22, 0x30, 0x0a, 0x01, 0x52, 0x12, 0x19, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x18, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10,
	0x01, 0x2a, 0x40, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x41, 0x52, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x41, 0x44,
	0x59, 0x10, 0x03, 0x2a, 0x27, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0d, 0x0a, 0x09, 0x57, 0x52, 0x49, 0x54, 0x45, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x45, 0x10, 0x01, 0x32, 0x9b, 0x01, 0x0a,
	0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x2b, 0x0a, 0x09, 0x67,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x0d, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x23, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x12, 0x09, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x09, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3b, 0x0a,
	0x11, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x11, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x78, 0x65, 0x63, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x78,
	0x65, 0x63, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x08, 0x2e, 0x2f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x90, 0x01, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_config_sync_proto_rawDescOnce sync.Once
	file_config_sync_proto_rawDescData = file_config_sync_proto_rawDesc
)

func file_config_sync_proto_rawDescGZIP() []byte {
	file_config_sync_proto_rawDescOnce.Do(func() {
		file_config_sync_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_sync_proto_rawDescData)
	})
	return file_config_sync_proto_rawDescData
}

var file_config_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_config_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_config_sync_proto_goTypes = []interface{}{
	(Code)(0),                // 0: Code
	(ServerStatus)(0),        // 1: ServerStatus
	(OrderType)(0),           // 2: OrderType
	(*HeartReq)(nil),         // 3: HeartReq
	(*Execute)(nil),          // 4: Execute
	(*UploadExecMsgReq)(nil), // 5: UploadExecMsgReq
	(*UploadExecMsgRes)(nil), // 6: UploadExecMsgRes
	(*HeartRes)(nil),         // 7: HeartRes
	(*APIConf)(nil),          // 8: APIConf
	(*GetConfigReq)(nil),     // 9: GetConfigReq
	(*GetConfigRes)(nil),     // 10: GetConfigRes
	(*R)(nil),                // 11: R
}
var file_config_sync_proto_depIdxs = []int32{
	1,  // 0: HeartReq.serverStatus:type_name -> ServerStatus
	2,  // 1: Execute.orderType:type_name -> OrderType
	11, // 2: HeartRes.r:type_name -> R
	4,  // 3: HeartRes.executes:type_name -> Execute
	11, // 4: GetConfigRes.r:type_name -> R
	8,  // 5: GetConfigRes.apiConf:type_name -> APIConf
	0,  // 6: R.code:type_name -> Code
	9,  // 7: ConfigSync.getConfig:input_type -> GetConfigReq
	3,  // 8: ConfigSync.sendHeart:input_type -> HeartReq
	5,  // 9: ConfigSync.uploadExecuteInfo:input_type -> UploadExecMsgReq
	10, // 10: ConfigSync.getConfig:output_type -> GetConfigRes
	7,  // 11: ConfigSync.sendHeart:output_type -> HeartRes
	6,  // 12: ConfigSync.uploadExecuteInfo:output_type -> UploadExecMsgRes
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_config_sync_proto_init() }
func file_config_sync_proto_init() {
	if File_config_sync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_sync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_sync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Execute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_sync_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadExecMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_sync_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadExecMsgRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_sync_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_sync_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_sync_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_sync_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConfigRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_sync_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*R); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_sync_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_sync_proto_goTypes,
		DependencyIndexes: file_config_sync_proto_depIdxs,
		EnumInfos:         file_config_sync_proto_enumTypes,
		MessageInfos:      file_config_sync_proto_msgTypes,
	}.Build()
	File_config_sync_proto = out.File
	file_config_sync_proto_rawDesc = nil
	file_config_sync_proto_goTypes = nil
	file_config_sync_proto_depIdxs = nil
}
