// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: config_sync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_OK   Code = 0
	Code_FAIL Code = 1
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "OK",
		1: "FAIL",
	}
	Code_value = map[string]int32{
		"OK":   0,
		"FAIL": 1,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_config_sync_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_config_sync_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{0}
}

type ServerStatus int32

const (
	ServerStatus_STARTING ServerStatus = 0
	ServerStatus_STARTED  ServerStatus = 1
	ServerStatus_FAILED   ServerStatus = 2
	ServerStatus_READY    ServerStatus = 3
)

// Enum value maps for ServerStatus.
var (
	ServerStatus_name = map[int32]string{
		0: "STARTING",
		1: "STARTED",
		2: "FAILED",
		3: "READY",
	}
	ServerStatus_value = map[string]int32{
		"STARTING": 0,
		"STARTED":  1,
		"FAILED":   2,
		"READY":    3,
	}
)

func (x ServerStatus) Enum() *ServerStatus {
	p := new(ServerStatus)
	*p = x
	return p
}

func (x ServerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_config_sync_proto_enumTypes[1].Descriptor()
}

func (ServerStatus) Type() protoreflect.EnumType {
	return &file_config_sync_proto_enumTypes[1]
}

func (x ServerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerStatus.Descriptor instead.
func (ServerStatus) EnumDescriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{1}
}

// 命令类型
type OrderType int32

const (
	OrderType_WRITEFILE OrderType = 0
	OrderType_EXECUTE   OrderType = 1
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "WRITEFILE",
		1: "EXECUTE",
	}
	OrderType_value = map[string]int32{
		"WRITEFILE": 0,
		"EXECUTE":   1,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_sync_proto_enumTypes[2].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_config_sync_proto_enumTypes[2]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{2}
}

type HeartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Machine       string                 `protobuf:"bytes,4,opt,name=machine,proto3" json:"machine,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	ServerStatus  ServerStatus           `protobuf:"varint,3,opt,name=serverStatus,proto3,enum=ServerStatus" json:"serverStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartReq) Reset() {
	*x = HeartReq{}
	mi := &file_config_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartReq) ProtoMessage() {}

func (x *HeartReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartReq.ProtoReflect.Descriptor instead.
func (*HeartReq) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{0}
}

func (x *HeartReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HeartReq) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *HeartReq) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HeartReq) GetServerStatus() ServerStatus {
	if x != nil {
		return x.ServerStatus
	}
	return ServerStatus_STARTING
}

type Execute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderType     OrderType              `protobuf:"varint,1,opt,name=orderType,proto3,enum=OrderType" json:"orderType,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=filePath,proto3" json:"filePath,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	BinInfo       string                 `protobuf:"bytes,5,opt,name=bin_info,json=binInfo,proto3" json:"bin_info,omitempty"`
	Args          []string               `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Execute) Reset() {
	*x = Execute{}
	mi := &file_config_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Execute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Execute) ProtoMessage() {}

func (x *Execute) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Execute.ProtoReflect.Descriptor instead.
func (*Execute) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{1}
}

func (x *Execute) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_WRITEFILE
}

func (x *Execute) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Execute) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Execute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Execute) GetBinInfo() string {
	if x != nil {
		return x.BinInfo
	}
	return ""
}

func (x *Execute) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type UploadExecMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadExecMsgReq) Reset() {
	*x = UploadExecMsgReq{}
	mi := &file_config_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadExecMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadExecMsgReq) ProtoMessage() {}

func (x *UploadExecMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadExecMsgReq.ProtoReflect.Descriptor instead.
func (*UploadExecMsgReq) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{2}
}

func (x *UploadExecMsgReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadExecMsgReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UploadExecMsgReq) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type UploadExecMsgRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadExecMsgRes) Reset() {
	*x = UploadExecMsgRes{}
	mi := &file_config_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadExecMsgRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadExecMsgRes) ProtoMessage() {}

func (x *UploadExecMsgRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadExecMsgRes.ProtoReflect.Descriptor instead.
func (*UploadExecMsgRes) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{3}
}

type HeartRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *R                     `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Executes      []*Execute             `protobuf:"bytes,3,rep,name=executes,proto3" json:"executes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartRes) Reset() {
	*x = HeartRes{}
	mi := &file_config_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartRes) ProtoMessage() {}

func (x *HeartRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartRes.ProtoReflect.Descriptor instead.
func (*HeartRes) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{4}
}

func (x *HeartRes) GetR() *R {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *HeartRes) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HeartRes) GetExecutes() []*Execute {
	if x != nil {
		return x.Executes
	}
	return nil
}

// 系统设置
type APIConf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIConf) Reset() {
	*x = APIConf{}
	mi := &file_config_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIConf) ProtoMessage() {}

func (x *APIConf) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIConf.ProtoReflect.Descriptor instead.
func (*APIConf) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{5}
}

func (x *APIConf) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type GetConfigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Sign          string                 `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigReq) Reset() {
	*x = GetConfigReq{}
	mi := &file_config_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigReq) ProtoMessage() {}

func (x *GetConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigReq.ProtoReflect.Descriptor instead.
func (*GetConfigReq) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{6}
}

func (x *GetConfigReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetConfigReq) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

type GetConfigRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *R                     `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Config        []*ConfigItem          `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	ApiConf       *APIConf               `protobuf:"bytes,4,opt,name=apiConf,proto3" json:"apiConf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRes) Reset() {
	*x = GetConfigRes{}
	mi := &file_config_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRes) ProtoMessage() {}

func (x *GetConfigRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRes.ProtoReflect.Descriptor instead.
func (*GetConfigRes) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{7}
}

func (x *GetConfigRes) GetR() *R {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *GetConfigRes) GetConfig() []*ConfigItem {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetConfigRes) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetConfigRes) GetApiConf() *APIConf {
	if x != nil {
		return x.ApiConf
	}
	return nil
}

type SaveConf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *GetConfigRes          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ConfigByte    []byte                 `protobuf:"bytes,3,opt,name=configByte,proto3" json:"configByte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConf) Reset() {
	*x = SaveConf{}
	mi := &file_config_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConf) ProtoMessage() {}

func (x *SaveConf) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConf.ProtoReflect.Descriptor instead.
func (*SaveConf) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{8}
}

func (x *SaveConf) GetConfig() *GetConfigRes {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SaveConf) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SaveConf) GetConfigByte() []byte {
	if x != nil {
		return x.ConfigByte
	}
	return nil
}

type ConfigItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItem) Reset() {
	*x = ConfigItem{}
	mi := &file_config_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItem) ProtoMessage() {}

func (x *ConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItem.ProtoReflect.Descriptor instead.
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigItem) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *ConfigItem) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type R struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=Code" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *R) Reset() {
	*x = R{}
	mi := &file_config_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *R) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*R) ProtoMessage() {}

func (x *R) ProtoReflect() protoreflect.Message {
	mi := &file_config_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use R.ProtoReflect.Descriptor instead.
func (*R) Descriptor() ([]byte, []int) {
	return file_config_sync_proto_rawDescGZIP(), []int{10}
}

func (x *R) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

func (x *R) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_config_sync_proto protoreflect.FileDescriptor

const file_config_sync_proto_rawDesc = "" +
	"\n" +
	"\x11config_sync.proto\x1a\x19google/protobuf/any.proto\"\x87\x01\n" +
	"\bHeartReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\amachine\x18\x04 \x01(\tR\amachine\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x121\n" +
	"\fserverStatus\x18\x03 \x01(\x0e2\r.ServerStatusR\fserverStatus\"\xa8\x01\n" +
	"\aExecute\x12(\n" +
	"\torderType\x18\x01 \x01(\x0e2\n" +
	".OrderTypeR\torderType\x12\x1a\n" +
	"\bfilePath\x18\x02 \x01(\tR\bfilePath\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x19\n" +
	"\bbin_info\x18\x05 \x01(\tR\abinInfo\x12\x12\n" +
	"\x04args\x18\x06 \x03(\tR\x04args\"D\n" +
	"\x10UploadExecMsgReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\"\x12\n" +
	"\x10UploadExecMsgRes\"\\\n" +
	"\bHeartRes\x12\x10\n" +
	"\x01r\x18\x01 \x01(\v2\x02.RR\x01r\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12$\n" +
	"\bexecutes\x18\x03 \x03(\v2\b.ExecuteR\bexecutes\"\x1d\n" +
	"\aAPIConf\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\"8\n" +
	"\fGetConfigReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04sign\x18\x02 \x01(\tR\x04sign\"\x83\x01\n" +
	"\fGetConfigRes\x12\x10\n" +
	"\x01r\x18\x01 \x01(\v2\x02.RR\x01r\x12#\n" +
	"\x06config\x18\x02 \x03(\v2\v.ConfigItemR\x06config\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\"\n" +
	"\aapiConf\x18\x04 \x01(\v2\b.APIConfR\aapiConf\"g\n" +
	"\bSaveConf\x12%\n" +
	"\x06config\x18\x01 \x01(\v2\r.GetConfigResR\x06config\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1e\n" +
	"\n" +
	"configByte\x18\x03 \x01(\fR\n" +
	"configByte\"P\n" +
	"\n" +
	"ConfigItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\"0\n" +
	"\x01R\x12\x19\n" +
	"\x04code\x18\x01 \x01(\x0e2\x05.CodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg*\x18\n" +
	"\x04Code\x12\x06\n" +
	"\x02OK\x10\x00\x12\b\n" +
	"\x04FAIL\x10\x01*@\n" +
	"\fServerStatus\x12\f\n" +
	"\bSTARTING\x10\x00\x12\v\n" +
	"\aSTARTED\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\t\n" +
	"\x05READY\x10\x03*'\n" +
	"\tOrderType\x12\r\n" +
	"\tWRITEFILE\x10\x00\x12\v\n" +
	"\aEXECUTE\x10\x012\x9b\x01\n" +
	"\n" +
	"ConfigSync\x12+\n" +
	"\tgetConfig\x12\r.GetConfigReq\x1a\r.GetConfigRes\"\x00\x12#\n" +
	"\tsendHeart\x12\t.HeartReq\x1a\t.HeartRes\"\x00\x12;\n" +
	"\x11uploadExecuteInfo\x12\x11.UploadExecMsgReq\x1a\x11.UploadExecMsgRes\"\x00B\rZ\b./;proto\x90\x01\x01b\x06proto3"

var (
	file_config_sync_proto_rawDescOnce sync.Once
	file_config_sync_proto_rawDescData []byte
)

func file_config_sync_proto_rawDescGZIP() []byte {
	file_config_sync_proto_rawDescOnce.Do(func() {
		file_config_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_sync_proto_rawDesc), len(file_config_sync_proto_rawDesc)))
	})
	return file_config_sync_proto_rawDescData
}

var file_config_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_config_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_config_sync_proto_goTypes = []any{
	(Code)(0),                // 0: Code
	(ServerStatus)(0),        // 1: ServerStatus
	(OrderType)(0),           // 2: OrderType
	(*HeartReq)(nil),         // 3: HeartReq
	(*Execute)(nil),          // 4: Execute
	(*UploadExecMsgReq)(nil), // 5: UploadExecMsgReq
	(*UploadExecMsgRes)(nil), // 6: UploadExecMsgRes
	(*HeartRes)(nil),         // 7: HeartRes
	(*APIConf)(nil),          // 8: APIConf
	(*GetConfigReq)(nil),     // 9: GetConfigReq
	(*GetConfigRes)(nil),     // 10: GetConfigRes
	(*SaveConf)(nil),         // 11: SaveConf
	(*ConfigItem)(nil),       // 12: ConfigItem
	(*R)(nil),                // 13: R
}
var file_config_sync_proto_depIdxs = []int32{
	1,  // 0: HeartReq.serverStatus:type_name -> ServerStatus
	2,  // 1: Execute.orderType:type_name -> OrderType
	13, // 2: HeartRes.r:type_name -> R
	4,  // 3: HeartRes.executes:type_name -> Execute
	13, // 4: GetConfigRes.r:type_name -> R
	12, // 5: GetConfigRes.config:type_name -> ConfigItem
	8,  // 6: GetConfigRes.apiConf:type_name -> APIConf
	10, // 7: SaveConf.config:type_name -> GetConfigRes
	0,  // 8: R.code:type_name -> Code
	9,  // 9: ConfigSync.getConfig:input_type -> GetConfigReq
	3,  // 10: ConfigSync.sendHeart:input_type -> HeartReq
	5,  // 11: ConfigSync.uploadExecuteInfo:input_type -> UploadExecMsgReq
	10, // 12: ConfigSync.getConfig:output_type -> GetConfigRes
	7,  // 13: ConfigSync.sendHeart:output_type -> HeartRes
	6,  // 14: ConfigSync.uploadExecuteInfo:output_type -> UploadExecMsgRes
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_config_sync_proto_init() }
func file_config_sync_proto_init() {
	if File_config_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_sync_proto_rawDesc), len(file_config_sync_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_sync_proto_goTypes,
		DependencyIndexes: file_config_sync_proto_depIdxs,
		EnumInfos:         file_config_sync_proto_enumTypes,
		MessageInfos:      file_config_sync_proto_msgTypes,
	}.Build()
	File_config_sync_proto = out.File
	file_config_sync_proto_goTypes = nil
	file_config_sync_proto_depIdxs = nil
}
