// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: v2fly_config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutBoundBuilder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Mux           int32                  `protobuf:"varint,2,opt,name=mux,proto3" json:"mux,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	WsPath        string                 `protobuf:"bytes,4,opt,name=ws_path,json=wsPath,proto3" json:"ws_path,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	VnextServerId string                 `protobuf:"bytes,6,opt,name=vnext_server_id,json=vnextServerId,proto3" json:"vnext_server_id,omitempty"`
	VnextAddr     string                 `protobuf:"bytes,7,opt,name=vnext_addr,json=vnextAddr,proto3" json:"vnext_addr,omitempty"`
	NginxPath     string                 `protobuf:"bytes,8,opt,name=nginx_path,json=nginxPath,proto3" json:"nginx_path,omitempty"`
	OpenSsl       bool                   `protobuf:"varint,13,opt,name=open_ssl,json=openSsl,proto3" json:"open_ssl,omitempty"`
	NginxPorts    []int32                `protobuf:"varint,9,rep,packed,name=nginx_ports,json=nginxPorts,proto3" json:"nginx_ports,omitempty"`
	Decryption    string                 `protobuf:"bytes,10,opt,name=decryption,proto3" json:"decryption,omitempty"`
	NginxBin      string                 `protobuf:"bytes,11,opt,name=nginx_bin,json=nginxBin,proto3" json:"nginx_bin,omitempty"`
	NginxArgs     []string               `protobuf:"bytes,12,rep,name=nginx_args,json=nginxArgs,proto3" json:"nginx_args,omitempty"`
	Grpc          *GRpc                  `protobuf:"bytes,15,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Mkcp          *MKcp                  `protobuf:"bytes,14,opt,name=mkcp,proto3" json:"mkcp,omitempty"`
	Certificates  *Certificate           `protobuf:"bytes,16,opt,name=certificates,proto3" json:"certificates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutBoundBuilder) Reset() {
	*x = OutBoundBuilder{}
	mi := &file_v2fly_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutBoundBuilder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutBoundBuilder) ProtoMessage() {}

func (x *OutBoundBuilder) ProtoReflect() protoreflect.Message {
	mi := &file_v2fly_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutBoundBuilder.ProtoReflect.Descriptor instead.
func (*OutBoundBuilder) Descriptor() ([]byte, []int) {
	return file_v2fly_config_proto_rawDescGZIP(), []int{0}
}

func (x *OutBoundBuilder) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *OutBoundBuilder) GetMux() int32 {
	if x != nil {
		return x.Mux
	}
	return 0
}

func (x *OutBoundBuilder) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *OutBoundBuilder) GetWsPath() string {
	if x != nil {
		return x.WsPath
	}
	return ""
}

func (x *OutBoundBuilder) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *OutBoundBuilder) GetVnextServerId() string {
	if x != nil {
		return x.VnextServerId
	}
	return ""
}

func (x *OutBoundBuilder) GetVnextAddr() string {
	if x != nil {
		return x.VnextAddr
	}
	return ""
}

func (x *OutBoundBuilder) GetNginxPath() string {
	if x != nil {
		return x.NginxPath
	}
	return ""
}

func (x *OutBoundBuilder) GetOpenSsl() bool {
	if x != nil {
		return x.OpenSsl
	}
	return false
}

func (x *OutBoundBuilder) GetNginxPorts() []int32 {
	if x != nil {
		return x.NginxPorts
	}
	return nil
}

func (x *OutBoundBuilder) GetDecryption() string {
	if x != nil {
		return x.Decryption
	}
	return ""
}

func (x *OutBoundBuilder) GetNginxBin() string {
	if x != nil {
		return x.NginxBin
	}
	return ""
}

func (x *OutBoundBuilder) GetNginxArgs() []string {
	if x != nil {
		return x.NginxArgs
	}
	return nil
}

func (x *OutBoundBuilder) GetGrpc() *GRpc {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *OutBoundBuilder) GetMkcp() *MKcp {
	if x != nil {
		return x.Mkcp
	}
	return nil
}

func (x *OutBoundBuilder) GetCertificates() *Certificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

type GRpc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRpc) Reset() {
	*x = GRpc{}
	mi := &file_v2fly_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRpc) ProtoMessage() {}

func (x *GRpc) ProtoReflect() protoreflect.Message {
	mi := &file_v2fly_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRpc.ProtoReflect.Descriptor instead.
func (*GRpc) Descriptor() ([]byte, []int) {
	return file_v2fly_config_proto_rawDescGZIP(), []int{1}
}

func (x *GRpc) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type Certificate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Path              string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	CaCertificate     string                 `protobuf:"bytes,1,opt,name=caCertificate,proto3" json:"caCertificate,omitempty"`
	CaKey             string                 `protobuf:"bytes,2,opt,name=caKey,proto3" json:"caKey,omitempty"`
	ClientCertificate string                 `protobuf:"bytes,3,opt,name=clientCertificate,proto3" json:"clientCertificate,omitempty"`
	ClientKey         string                 `protobuf:"bytes,4,opt,name=clientKey,proto3" json:"clientKey,omitempty"`
	ServerCertificate string                 `protobuf:"bytes,5,opt,name=serverCertificate,proto3" json:"serverCertificate,omitempty"`
	ServerKey         string                 `protobuf:"bytes,6,opt,name=serverKey,proto3" json:"serverKey,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_v2fly_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_v2fly_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_v2fly_config_proto_rawDescGZIP(), []int{2}
}

func (x *Certificate) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Certificate) GetCaCertificate() string {
	if x != nil {
		return x.CaCertificate
	}
	return ""
}

func (x *Certificate) GetCaKey() string {
	if x != nil {
		return x.CaKey
	}
	return ""
}

func (x *Certificate) GetClientCertificate() string {
	if x != nil {
		return x.ClientCertificate
	}
	return ""
}

func (x *Certificate) GetClientKey() string {
	if x != nil {
		return x.ClientKey
	}
	return ""
}

func (x *Certificate) GetServerCertificate() string {
	if x != nil {
		return x.ServerCertificate
	}
	return ""
}

func (x *Certificate) GetServerKey() string {
	if x != nil {
		return x.ServerKey
	}
	return ""
}

type MKcp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Mtu              int32                  `protobuf:"varint,1,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Tti              int32                  `protobuf:"varint,2,opt,name=tti,proto3" json:"tti,omitempty"`
	UplinkCapacity   int32                  `protobuf:"varint,3,opt,name=uplinkCapacity,proto3" json:"uplinkCapacity,omitempty"`
	DownlinkCapacity int32                  `protobuf:"varint,4,opt,name=downlinkCapacity,proto3" json:"downlinkCapacity,omitempty"`
	Congestion       bool                   `protobuf:"varint,5,opt,name=congestion,proto3" json:"congestion,omitempty"`
	ReadBufferSize   int32                  `protobuf:"varint,6,opt,name=readBufferSize,proto3" json:"readBufferSize,omitempty"`
	WriteBufferSize  int32                  `protobuf:"varint,7,opt,name=writeBufferSize,proto3" json:"writeBufferSize,omitempty"`
	Header           *MKcpHeader            `protobuf:"bytes,8,opt,name=header,proto3" json:"header,omitempty"`
	Seed             string                 `protobuf:"bytes,9,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MKcp) Reset() {
	*x = MKcp{}
	mi := &file_v2fly_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MKcp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MKcp) ProtoMessage() {}

func (x *MKcp) ProtoReflect() protoreflect.Message {
	mi := &file_v2fly_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MKcp.ProtoReflect.Descriptor instead.
func (*MKcp) Descriptor() ([]byte, []int) {
	return file_v2fly_config_proto_rawDescGZIP(), []int{3}
}

func (x *MKcp) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *MKcp) GetTti() int32 {
	if x != nil {
		return x.Tti
	}
	return 0
}

func (x *MKcp) GetUplinkCapacity() int32 {
	if x != nil {
		return x.UplinkCapacity
	}
	return 0
}

func (x *MKcp) GetDownlinkCapacity() int32 {
	if x != nil {
		return x.DownlinkCapacity
	}
	return 0
}

func (x *MKcp) GetCongestion() bool {
	if x != nil {
		return x.Congestion
	}
	return false
}

func (x *MKcp) GetReadBufferSize() int32 {
	if x != nil {
		return x.ReadBufferSize
	}
	return 0
}

func (x *MKcp) GetWriteBufferSize() int32 {
	if x != nil {
		return x.WriteBufferSize
	}
	return 0
}

func (x *MKcp) GetHeader() *MKcpHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MKcp) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

type MKcpHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MKcpHeader) Reset() {
	*x = MKcpHeader{}
	mi := &file_v2fly_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MKcpHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MKcpHeader) ProtoMessage() {}

func (x *MKcpHeader) ProtoReflect() protoreflect.Message {
	mi := &file_v2fly_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MKcpHeader.ProtoReflect.Descriptor instead.
func (*MKcpHeader) Descriptor() ([]byte, []int) {
	return file_v2fly_config_proto_rawDescGZIP(), []int{4}
}

func (x *MKcpHeader) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_v2fly_config_proto protoreflect.FileDescriptor

const file_v2fly_config_proto_rawDesc = "" +
	"\n" +
	"\x12v2fly_config.proto\x1a\x19google/protobuf/any.proto\"\xe4\x03\n" +
	"\x0fOutBoundBuilder\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x10\n" +
	"\x03mux\x18\x02 \x01(\x05R\x03mux\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x17\n" +
	"\aws_path\x18\x04 \x01(\tR\x06wsPath\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12&\n" +
	"\x0fvnext_server_id\x18\x06 \x01(\tR\rvnextServerId\x12\x1d\n" +
	"\n" +
	"vnext_addr\x18\a \x01(\tR\tvnextAddr\x12\x1d\n" +
	"\n" +
	"nginx_path\x18\b \x01(\tR\tnginxPath\x12\x19\n" +
	"\bopen_ssl\x18\r \x01(\bR\aopenSsl\x12\x1f\n" +
	"\vnginx_ports\x18\t \x03(\x05R\n" +
	"nginxPorts\x12\x1e\n" +
	"\n" +
	"decryption\x18\n" +
	" \x01(\tR\n" +
	"decryption\x12\x1b\n" +
	"\tnginx_bin\x18\v \x01(\tR\bnginxBin\x12\x1d\n" +
	"\n" +
	"nginx_args\x18\f \x03(\tR\tnginxArgs\x12\x19\n" +
	"\x04grpc\x18\x0f \x01(\v2\x05.GRpcR\x04grpc\x12\x19\n" +
	"\x04mkcp\x18\x0e \x01(\v2\x05.MKcpR\x04mkcp\x120\n" +
	"\fcertificates\x18\x10 \x01(\v2\f.certificateR\fcertificates\"(\n" +
	"\x04GRpc\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\"\xf5\x01\n" +
	"\vcertificate\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12$\n" +
	"\rcaCertificate\x18\x01 \x01(\tR\rcaCertificate\x12\x14\n" +
	"\x05caKey\x18\x02 \x01(\tR\x05caKey\x12,\n" +
	"\x11clientCertificate\x18\x03 \x01(\tR\x11clientCertificate\x12\x1c\n" +
	"\tclientKey\x18\x04 \x01(\tR\tclientKey\x12,\n" +
	"\x11serverCertificate\x18\x05 \x01(\tR\x11serverCertificate\x12\x1c\n" +
	"\tserverKey\x18\x06 \x01(\tR\tserverKey\"\xa9\x02\n" +
	"\x04MKcp\x12\x10\n" +
	"\x03mtu\x18\x01 \x01(\x05R\x03mtu\x12\x10\n" +
	"\x03tti\x18\x02 \x01(\x05R\x03tti\x12&\n" +
	"\x0euplinkCapacity\x18\x03 \x01(\x05R\x0euplinkCapacity\x12*\n" +
	"\x10downlinkCapacity\x18\x04 \x01(\x05R\x10downlinkCapacity\x12\x1e\n" +
	"\n" +
	"congestion\x18\x05 \x01(\bR\n" +
	"congestion\x12&\n" +
	"\x0ereadBufferSize\x18\x06 \x01(\x05R\x0ereadBufferSize\x12(\n" +
	"\x0fwriteBufferSize\x18\a \x01(\x05R\x0fwriteBufferSize\x12#\n" +
	"\x06header\x18\b \x01(\v2\v.MKcpHeaderR\x06header\x12\x12\n" +
	"\x04seed\x18\t \x01(\tR\x04seed\" \n" +
	"\n" +
	"MKcpHeader\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04typeB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_v2fly_config_proto_rawDescOnce sync.Once
	file_v2fly_config_proto_rawDescData []byte
)

func file_v2fly_config_proto_rawDescGZIP() []byte {
	file_v2fly_config_proto_rawDescOnce.Do(func() {
		file_v2fly_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2fly_config_proto_rawDesc), len(file_v2fly_config_proto_rawDesc)))
	})
	return file_v2fly_config_proto_rawDescData
}

var file_v2fly_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v2fly_config_proto_goTypes = []any{
	(*OutBoundBuilder)(nil), // 0: OutBoundBuilder
	(*GRpc)(nil),            // 1: GRpc
	(*Certificate)(nil),     // 2: certificate
	(*MKcp)(nil),            // 3: MKcp
	(*MKcpHeader)(nil),      // 4: MKcpHeader
}
var file_v2fly_config_proto_depIdxs = []int32{
	1, // 0: OutBoundBuilder.grpc:type_name -> GRpc
	3, // 1: OutBoundBuilder.mkcp:type_name -> MKcp
	2, // 2: OutBoundBuilder.certificates:type_name -> certificate
	4, // 3: MKcp.header:type_name -> MKcpHeader
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v2fly_config_proto_init() }
func file_v2fly_config_proto_init() {
	if File_v2fly_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2fly_config_proto_rawDesc), len(file_v2fly_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2fly_config_proto_goTypes,
		DependencyIndexes: file_v2fly_config_proto_depIdxs,
		MessageInfos:      file_v2fly_config_proto_msgTypes,
	}.Build()
	File_v2fly_config_proto = out.File
	file_v2fly_config_proto_goTypes = nil
	file_v2fly_config_proto_depIdxs = nil
}
